### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by joshuadanpeterson** [fanghuiz/ufc-stats-crawler#1]
After installing the dependencies, I ran the scraper in the project directory, only to get this traceback and FileNotFoundError:

```
Traceback (most recent call last):
  File "/Users/<username>/anaconda3/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/Users/<username>/anaconda3/lib/python3.7/site-packages/scrapy/cmdline.py", line 149, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/Users/<username>/anaconda3/lib/python3.7/site-packages/scrapy/crawler.py", line 253, in __init__
    configure_logging(self.settings, install_root_handler)
  File "/Users/<username>/anaconda3/lib/python3.7/site-packages/scrapy/utils/log.py", line 101, in configure_logging
    install_scrapy_root_handler(settings)
  File "/Users/<username>/anaconda3/lib/python3.7/site-packages/scrapy/utils/log.py", line 111, in install_scrapy_root_handler
    _scrapy_root_handler = _get_handler(settings)
  File "/Users/<username>/anaconda3/lib/python3.7/site-packages/scrapy/utils/log.py", line 127, in _get_handler
    handler = logging.FileHandler(filename, encoding=encoding)
  File "/Users/<username>/anaconda3/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Users/<username>/anaconda3/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/<username>/PATH/ufc-stats-crawler/log/2020-02-06T00-35-00.log'
```

From what I can find on the different forums, the FileNotFoundError means that there's an issue of something pointing to a relative path instead of an absolute path, but this is where I'm a bit lost. Do I need to modify one of the scripts and change something to an absolute path?

Sorry if this is a relatively easy fix and I'm just not seeing it. Thanks for building this crawler.

**Comment by fanghuiz** [comment]
Hi Josh, I think it's because the `log` directory to store logs is missing, I've modified the settings to create the directory automatically (rookie mistake on my part!). Also added a `requirements.txt` to install the dependencies. 

Let me know if it is working now. And if you make something cool with the data!

**Comment by joshuadanpeterson** [comment]
It works brilliantly now, thank you!

> Let me know if it is working now. And if you make something cool with the data!

Will do!
